CREATE TABLE "tag" (
  "id"        INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name"      VARCHAR(128) NOT NULL,
  "parent_id" INTEGER,
  UNIQUE("name", "parent_id"),
  FOREIGN KEY("parent_id") REFERENCES "tag"("id")
);

CREATE TABLE "file" (
  "id"        INTEGER      PRIMARY KEY,
  "filename"  TEXT         UNIQUE NOT NULL
);

CREATE TABLE "image" (
  "id"        INTEGER      PRIMARY KEY,
  "width"     INTEGER      NOT NULL,
  "height"    INTEGER      NOT NULL,
  FOREIGN KEY("id") REFERENCES "file"("id")
);

CREATE TABLE "photo" (
  "id"        INTEGER      PRIMARY KEY,
  "exposure_time" INTEGER, 
  FOREIGN KEY("id") REFERENCES "image"("id")
);

CREATE TABLE "file_tag_xref" (
  "file_id"   INTEGER      NOT NULL,
  "tag_id"    INTEGER      NOT NULL,
  PRIMARY KEY("file_id", "tag_id"),
  FOREIGN KEY("file_id") REFERENCES "file"("id"),
  FOREIGN KEY("tag_id") REFERENCES "tag"("id")
);
